### ISSUE TITLE
process.nextTick

### ISSUE THREAD

**Issue by orourkedd** [brianc/node-pg-query-stream#10]
Should this be setImmediate() now?

**Comment by orourkedd** [comment]
I'm not sure if it matters in this case because there is not any io that will be blocked.  I'm curious, what is process.nextTick used for here?

**Comment by brianc** [comment]
Is using `process.nextTick` over `setImmediate` causing you any issues?  It's a way to have the stream interface conform exactly to the node readable stream interface. The readable stream is a tricky beast and certain events need to be emitted in a certain order.  Using `process.nextTick` just allows easier support for node v0.8.x which I want to keep around until node v0.12.x is release and the whole io.js thing stabilizes a bit.

**Comment by orourkedd** [comment]
Thanks for the response. It's not causing any issues. I was reading your sources because I was having another problem (which was my own) and came across it.  I'm not familiar w 0.8 so I didn't know what I was looking at.  Thanks again.

**Comment by brianc** [comment]
No problemo!
