### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-pg-query-stream#11]
Trying to add support for this library to pg-promise, just wanted to ask...

Is it correct to use the following two event traps to handle all situations?

``` javascript
stream.once('end', finishHandler);
stream.once('error', errorHandler);
```

Is `once` sufficient when using this library? Or is it possible that we need the handlers more than once?

**Comment by brianc** [comment]
I think once should be sufficient. Sorry for the delay in responding: just saw this.
