### ISSUE TITLE
Can this be used for inserts as well?

### ISSUE THREAD

**Issue by flesler** [brianc/node-pg-query-stream#14]
Question above.
From the docs I take it can't, is that something that is planned to be added?

**Comment by brianc** [comment]
The postgres protocol doesn't support inserts in a stream.  You can use https://github.com/brianc/node-pg-copy-streams for streaming writes, but the semantics are a lot different than a normal query.  I usually use `async` or if I need to batch write a ton of data pg-copy-streams or even `pg_restore` from the command-line.

**Comment by Globik** [comment]
Is pg-stream just like pipelinedb which is based on postgresql?
