### ISSUE TITLE
End Event Before Last Record Of Data

### ISSUE THREAD

**Issue by rbadillo** [brianc/node-pg-query-stream#20]
Hi Man,

I want to report that this issue is back:
https://github.com/brianc/node-pg-query-stream/issues/3

This is my sample code:

``` JavaScript
var pg = require('pg');
var QueryStream = require('pg-query-stream');

// DB Settings
var conString = "postgres://..........";
var client = new pg.Client(conString);

client.connect(function(err) {
  if(err) 
  {
    return console.error('could not connect to database', err);
  }

  querySelect = "SELECT * from test LIMIT 5";

  var queryStream = new QueryStream(querySelect);
  var queryObj = client.query(queryStream)
  var counter=0

  queryObj
  .on('error',function(err){
    console.log("Error")
    console.log(err)
  })

  .on('data',function(rec){

    queryObj.pause()

    var sleep = function() {
        counter +=1
        console.log("Data: " +counter)
        queryObj.resume();
      }

    setTimeout(sleep,1000);
  })

  .on('end',function(){
    console.log("End")
    client.end()
  })
});
```

This is the output:

Data: 1
Data: 2
Data: 3
Data: 4
End
Data: 5

Operating System:
CentOS 6.5 Final

Node Version:
v0.10.26

Can you help me with this issue as soon as possible please ?

Regards,
Roberto

**Comment by brianc** [comment]
Hey Roberto -

In your code you're doing a `console.log` in a sleep of 1 second after the actual data event is fired & the callback receives the data.  Try putting the log outside the `sleep` function - I bet you'll see the data event happening before the end event. 😄

**Comment by rbadillo** [comment]
Hi Brian, I see your point but I'm using queryObj.pause()  and queryObj.resume() to avoid the event from being called.

Basically, I'm forcing the next data event to wait until I call queryObj.resume().

Do you agree with me know ?

**Comment by cyberjoac** [comment]
+1

**Comment by cyberjoac** [comment]
Thanks for the great work ! 
I've got an issue in this code: 

```
        // Stream results back one row at a time
        stream.on('data', function (row) {
            rowCount++;
            rowsBuffer.push(row);

            if (rowsBuffer.length == BUFFER_SIZE) {
                stream.pause();
                // Flush
                processRows(rowsBuffer, function (err, results) {
                    rowsBuffer = [];
                    stream.resume();
                });
            }
        });

        // After all data is returned, close connection and return results
        stream.on('end', function () {
            processRows(rowsBuffer, function (err, result) {
                done();
                return postgresQueryCallback(null, rowCount);
            });
```

stream.on('end', ...)
gets called before the stream 'resumes' and therefore it still have elements in rowsBuffer when in 'end'.

Thanks for your help

**Comment by LinusU** [comment]
Another way is to pipe into a `Writeable` stream that signals when it has processed a records, then listen to the `finish` event of that stream.

```js
const { Writeable } = require('streams')
const QueryStream = require('pg-query-stream')

// ...

const query = new QueryStream(...)
const stream = client.query(query)

stream.pipe(new Writeable({
  objectMode: true,
  write (row, _, cb) {
    // Do something with the rows, then call cb
    processRow(row, cb)
  }
})).on('finish', () => {
  console.log('Done')
})
```

**Comment by mzalazar** [comment]
duh... is this a BUG or what? i was thinking about using this module, but... by reading this comments i had change my mind. By the way, i'm going to wait for some solution for this, or at least some example code to do things right.

**Comment by LinusU** [comment]
> duh... is this a BUG or what?

This is not a bug at all, this is how streams work. There would be no way for this module to do anything differently since there is no signal to indicate that processing is done.

No `data` event is fired after the `end` event, but since there is a `setTimeout` call in the `.on('data', ...)` handler, that is logged later, after the `end` log has already printed.

I would suggest to use a `Writeable` stream if you need to know when all records has been processed, per my previous comment. That would work with any other `Readable` stream as well, since it's following the Node.js standards...

**Comment by mzalazar** [comment]
@LinusU I understand, BIG thanks for your explanation!!!! ;-)

**Comment by LinusU** [comment]
Happy to help :)

**Comment by brianc** [comment]
Thanks for your help @LinusU! 😘
