### ISSUE TITLE
This library does NOT use the latest pg-cursor

### ISSUE THREAD

**Issue by cscalfani** [brianc/node-pg-query-stream#25]
This is causing a problem with empty queries which was fixed between 1.0.0 (version being still used here) and 1.2.0 (the latest) of pg-cursor.

Can you please update to the latest pg-cursor. Thanks.

**Comment by brianc** [comment]
I'm backed up with node-postgres stuff at the moment, but I'm open to reviewing a pull request if you put one together!  Otherwise, it'll have to wait for a while.

**Comment by brianc** [comment]
This will be fixed with #29 today!

**Comment by cscalfani** [comment]
Thanks!!
