### ISSUE TITLE
Number of rows?

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-pg-query-stream#30]
When I did support of this library's v1.0 within `pg-promise`, I had to add a hack (code injection) for the read operation (method `_fetch`) in order to pull such basic information as the number of rows that went through the stream.

With version 1.1, do I have to write a new hack for it or is there now a civilized approach to getting the number of rows once the streaming has finished?

---

This is the hack that I had to do for v1.0:

```js
    let stream, fetch, nRows = 0;
    try {
        stream = client.query(qs);
        fetch = stream._fetch;
        stream._fetch = (size, func) => {
            fetch.call(stream, size, (err, rows) => {
                if (!err && rows.length) {
                    nRows += rows.length;
                    if (error) {
                        stream.close();
                    }
                }
                return func(err, rows);
            });
        };
    } catch (err) {
        error = err;
    }
```

**Comment by vitaly-t** [comment]
This is directly related to: #12.

**Comment by vitaly-t** [comment]
I kind of have figured it out... by doing `stream.on('data', ()=>{/* do internal incrementing */})`.

**Comment by brianc** [comment]
Yeah, if you are reading from a stream and want to know how many records are coming in from the stream its trivial to keep a counter of rows as you read them from the stream.  That's the recommended approach AFAIK.

**Comment by brianc** [comment]
You could use something like [through2](https://www.npmjs.com/package/through2) to pipe the stream into, and in your stream push all incoming data back out, but also increment a counter internally to that stream.
