### ISSUE TITLE
eslint should not be dependencies

### ISSUE THREAD

**Issue by cheeweep** [brianc/node-pg-query-stream#31]
In 1.1.0 eslint-* is included as dependencies. Surely that is wrong.

**Comment by brianc** [comment]
Oofff good call - sorry about that will fix right away.

**Comment by brianc** [comment]
Thanks for pointing this out. I've got a [pull request](https://github.com/brianc/node-pg-query-stream/pull/33) open to fix this.  I'll publish a new patch version out in a second.

If you or your company benefit from node-postgres and have the means, please consider supporting my work on [Patreon](https://www.patreon.com/node_postgres).

**Comment by brianc** [comment]
Published fix at `pg-query-stream@1.1.1`
