### ISSUE TITLE
Not compatible with pg 7.50

### ISSUE THREAD

**Issue by Equals182** [brianc/node-pg-query-stream#46]
This module became incompatible with pg's 'minor' update 7.5.0.
[Here](https://github.com/brianc/node-postgres/commit/3828aa86081491282c118884c245b4a19619f02e#diff-32a8cfb1af74860f3233cd24dcd57fadR147) you can see changes in `query.submit` function - it now returns `null` or `Error`, while current [pg-query-stream returns **this**](https://github.com/brianc/node-pg-query-stream/blob/master/index.js#L24)
This basically breaks the whole streaming thing.
I believe returning `null` should be enough to fix this issue.

**Comment by brianc** [comment]
Thanks! Sorry about that, will fix today.

**Comment by brianc** [comment]
Pushed a new patch version w/ the fix!
