### ISSUE TITLE
How to handle errors on queries?

### ISSUE THREAD

**Issue by volkanunsal** [brianc/node-pg-query-stream#9]
I'm curious how to handle an error generated while running the query in the pipe.

```coffeescript
stream = client.query(q)
stream.on 'end', done
stream
  .pipe(JSONStream.stringify())
  .pipe(through2.obj((result)->
     ....

```

**Comment by whitelynx** [comment]
Taking a quick glance at the source, it looks like you should just need to handle the `error` event on the stream:
```javascript
var stream = client.query(q)
    .on('end', done)
    .on('error', onError)
```

Since streams propagate errors, you should be able to attach your event handlers even after your `.pipe()` calls if you wish.

**Comment by volkanunsal** [comment]
Thanks @whitelynx
